name: Build
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      
      - name: Test
        run: ./scripts/test

      - name: Build
        run: ./scripts/build
        env:
          CROSS: "1"

