name: Publish
on:
  release:
    types:
      - published
permissions:
    contents: write
    id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: ./scripts/build
        env:
          VERSION: ${{ github.ref_name }}
          CROSS: "1"

      - name: Upload Release Assets
        run: gh release upload ${{ github.ref_name }} bin/*
        env:
          GH_TOKEN: ${{ github.token }}
